// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogpvdhsacrxscpxgndfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ncHZkaHNhY3J4c2NweGduZGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MzE5NzgsImV4cCI6MjA1NTQwNzk3OH0.-1Oux5zedurOJ-0C4VhUeA1gT_Z43sYWzMFXOpz2MTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);