// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucnfkqyhepotnwjedcgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbmZrcXloZXBvdG53amVkY2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNjY0OTAsImV4cCI6MjA1NDY0MjQ5MH0.2orFNVsms-YEIiyDxc7qFM5RlaBKY3G6_u-Tl9Fn0tI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);